### ISSUE TITLE
Issue installing on OSX

### ISSUE THREAD

**Issue by lawrenceleejr** [yadage/yadage#70]
Hi!

Just wanted to post that I had issues installing `yadage` via `pip`. I had been getting errors as in the attached output log ([output.txt](https://github.com/yadage/yadage/files/2567414/output.txt)) from a simple `pip install yadage`. After googling around for a bit, I finally found that manually updating `jq` to its HEAD fixed the issue as done in:

https://github.com/doloopwhile/pyjq/issues/1

After the `jq` install was finished, the straightforward `pip install` worked fine.

Just in case this comes up -- If others run into this, it might be good to have a note in the docs?

Thanks!
-Larry

**Comment by lawrenceleejr** [comment]
Slightly different point: It seems to not work under python3. Might be good to add a check to enforce < 3?

Thanks!
-L

**Comment by lukasheinrich** [comment]
Hi Larry,

thanks for these pointers. I'll check. in The CI we do explicitly check python3 and python2.. In any case we do also have docker images for yadage so that you do not need to deal with installing it either. I'll add docs on how to use the docker images

**Comment by matthewfeickert** [comment]
@lukasheinrich So we can close this Issue out, can you verify that

```console
python3 -m venv venv && . venv/bin/activate
python -m pip --quiet install --upgrade pip setuptools wheel
python -m pip install yadage
```

now works on macOS? I assume yes, as `yadage` is Python 3 only now, but we only test on Linux in CI.

**Comment by matthewfeickert** [comment]
@dantrim confirmed things are working on macOS now. Thanks @dantrim!

Closing now! :) :rocket:
